package com.beautyfinder.b2b.domain.audit

enum class AuditAction {
    // Auth
    LOGIN_SUCCESS, LOGIN_FAILED, LOGOUT, PASSWORD_CHANGED, PASSWORD_RESET,
    ACCOUNT_LOCKED, TOKEN_REFRESHED,

    // Appointments
    APPOINTMENT_CREATED, APPOINTMENT_STATUS_CHANGED, APPOINTMENT_RESCHEDULED,
    APPOINTMENT_CANCELLED,

    // Clients
    CLIENT_CREATED, CLIENT_UPDATED, CLIENT_SENSITIVE_DATA_ACCESSED,
    CLIENT_SENSITIVE_DATA_UPDATED, CLIENT_BLACKLISTED, CLIENT_UNBLACKLISTED,
    GDPR_CONSENT_RECORDED, GDPR_CONSENT_REVOKED, CLIENT_DATA_EXPORTED,

    // Employees
    EMPLOYEE_CREATED, EMPLOYEE_UPDATED, EMPLOYEE_DEACTIVATED,
    SCHEDULE_UPDATED, SCHEDULE_EXCEPTION_ADDED,

    // Services
    SERVICE_CREATED, SERVICE_UPDATED, SERVICE_ARCHIVED,
    VARIANT_CREATED, VARIANT_UPDATED, VARIANT_DEACTIVATED,

    // Settings
    SALON_SETTINGS_UPDATED, OPENING_HOURS_UPDATED,
    LOYALTY_SETTINGS_UPDATED, INTEGRATION_SETTINGS_UPDATED,

    // Users
    USER_INVITED, USER_ACTIVATED, USER_ROLE_CHANGED, USER_DEACTIVATED,

    // Billing
    INVOICE_GENERATED, INVOICE_PAID, REPORT_GENERATED,

    // System
    SYSTEM_AUTO_COMPLETE, SYSTEM_MONTHLY_BILLING, DATA_IMPORT,
}
